"""Seed agent specs. Mirrors the front-end roster so both stays in sync."""
from __future__ import annotations

from apps.api.models.schemas import AgentSpec, AgentStats, AgentStatus

_DEFAULT_STATS = AgentStats(
    tasks_completed_today=3,
    tasks_total=120,
    success_rate=0.93,
    avg_confidence=0.88,
    tools_used_today=12,
    avg_duration_ms=4200,
)


def _spec(**kwargs) -> AgentSpec:
    payload = {
        "personality": "",
        "icon": "🤖",
        "color": "#6366f1",
        "allowed_tools": [],
        "allowed_tool_categories": [],
        "max_concurrent_tasks": 5,
        "max_iterations_per_task": 5,
        "escalation_threshold": 0.6,
        "sop_document_ids": [],
        "can_delegate_to": [],
        "approval_authority": [],
        "active": True,
        "status": AgentStatus.idle,
        "stats": _DEFAULT_STATS,
        **kwargs,
    }
    return AgentSpec.model_validate(payload)


SEED_AGENTS: list[AgentSpec] = [
    _spec(
        agent_id="supervisor", name="CEO Agent (Supervisor)",
        role="Orkestratör — TicOSClaw",
        goal="Görevleri analiz et, alt ajanlara dağıt, sonuçları birleştir.",
        personality="Stratejik, organize, sakin, net.", icon="👔", color="#6366f1",
        can_delegate_to=[
            "market_research_agent", "brand_identity_agent", "product_development_agent",
            "store_setup_agent", "catalog_agent", "pricing_agent", "marketing_agent",
            "content_seo_agent", "email_crm_agent", "operations_agent", "support_agent",
            "review_reputation_agent", "analytics_agent", "growth_agent",
            "legal_compliance_agent", "influencer_pr_agent",
            "negotiation_agent", "logistics_agent", "dynamic_pricing_agent",
            "autonomous_decision_agent",
        ],
        status=AgentStatus.active,
    ),
    _spec(
        agent_id="market_research_agent", name="Market Research Agent",
        role="Pazar & Rakip Araştırmacısı",
        goal="Pazar büyüklüğü, talep ve rakip dinamiklerini ölç; 'girilmeli mi' skoru üret.",
        personality="Meraklı, kanıt odaklı.", icon="🔬", color="#22d3ee",
        allowed_tools=[
            "google_trends_query", "competitor_profile_builder", "niche_scorer",
            "demand_estimator", "competitor_review_analyzer", "competitor_report_builder",
        ],
        allowed_tool_categories=["research"],
    ),
    _spec(
        agent_id="brand_identity_agent", name="Brand Identity Agent",
        role="Marka Kimliği & Konumlandırma",
        goal="İsim, ton, hikaye, renk paleti, persona inşa et.",
        personality="Yaratıcı, hikayeci.", icon="🎨", color="#f472b6",
        allowed_tools=["brand_name_generator", "color_palette_generator", "target_persona_builder"],
        allowed_tool_categories=["brand"],
    ),
    _spec(
        agent_id="product_development_agent", name="Product Development Agent",
        role="Ürün Geliştirme & Tedarik",
        goal="Tedarikçi bul, numune planla, COGS hesapla.",
        personality="Pratik, müzakereci.", icon="🧪", color="#84cc16",
        allowed_tools=["alibaba_supplier_search", "cogs_calculator"],
        allowed_tool_categories=["product"],
    ),
    _spec(
        agent_id="store_setup_agent", name="Store Setup Agent",
        role="Mağaza & Kanal Kurulum",
        goal="Shopify/pazaryeri kurulumu, tema, yasal sayfalar.",
        personality="Sistematik.", icon="🏗️", color="#eab308",
        allowed_tools=["shopify_store_create", "trendyol_seller_onboard_guide"],
        allowed_tool_categories=["store"],
    ),
    _spec(
        agent_id="catalog_agent", name="Catalog Agent",
        role="Ürün Kataloğu Yöneticisi",
        goal="Ürün verilerinin eksiksiz, tutarlı, optimize olmasını sağla.",
        personality="Detaycı.", icon="📦", color="#f59e0b",
        allowed_tools=["category_mapper", "image_analysis"],
        allowed_tool_categories=["catalog"],
    ),
    _spec(
        agent_id="pricing_agent", name="Pricing Agent",
        role="Fiyatlandırma Stratejisti",
        goal="Rekabetçi ve kârlı fiyatlama.",
        personality="Analitik, veri odaklı.", icon="💰", color="#10b981",
        allowed_tools=["margin_calculator", "competitor_price_lookup", "campaign_discount_simulator"],
        allowed_tool_categories=["pricing"],
    ),
    _spec(
        agent_id="marketing_agent", name="Marketing Agent",
        role="Kampanya & Reklam Stratejisti",
        goal="Reklam ve kampanya planı + optimizasyon.",
        personality="Yaratıcı, sonuç odaklı.", icon="📣", color="#ec4899",
        allowed_tools=["meta_ads_get_campaigns", "google_ads_get_campaigns", "budget_allocator"],
        allowed_tool_categories=["marketing"],
    ),
    _spec(
        agent_id="content_seo_agent", name="Content & SEO Agent",
        role="İçerik & SEO",
        goal="SEO uyumlu, marka tonunda içerik üret.",
        personality="Yaratıcı, dil duyarlı.", icon="✍️", color="#8b5cf6",
        allowed_tools=["seo_keyword_research", "content_generator"],
        allowed_tool_categories=["content_seo"],
    ),
    _spec(
        agent_id="email_crm_agent", name="Email & CRM Agent",
        role="E-posta, SMS, Sadakat",
        goal="Otomasyon akışları, segmentler, win-back/referral.",
        personality="Disiplinli.", icon="✉️", color="#7c3aed",
        allowed_tools=["klaviyo_flow_setup_guide", "email_sequence_writer", "segment_builder"],
        allowed_tool_categories=["email"],
    ),
    _spec(
        agent_id="operations_agent", name="Operations Agent",
        role="Sipariş, Kargo, Stok",
        goal="Operasyonel verimliliği koru.",
        personality="Sistematik.", icon="⚙️", color="#f97316",
        allowed_tools=["order_list", "stock_levels_query", "stock_forecast", "agent_handoff"],
        allowed_tool_categories=["order", "stock"],
    ),
    _spec(
        agent_id="support_agent", name="Customer Support Agent",
        role="Müşteri Hizmetleri",
        goal="Mesajları hızlı ve doğru şekilde yanıtla.",
        personality="Empatik, sabırlı.", icon="🎧", color="#06b6d4",
        allowed_tools=["support_inbox_fetch", "sentiment_analyzer", "draft_reply_generator"],
        allowed_tool_categories=["support"],
    ),
    _spec(
        agent_id="review_reputation_agent", name="Review & Reputation Agent",
        role="Yorum & İtibar",
        goal="Yorumları topla, taslak yanıt üret, itibar puanı çıkar.",
        personality="Diplomat, empatik.", icon="⭐", color="#fbbf24",
        allowed_tools=["review_aggregator", "review_sentiment_analyzer", "review_response_generator"],
        allowed_tool_categories=["review"],
    ),
    _spec(
        agent_id="analytics_agent", name="Analytics Agent",
        role="Veri Analisti",
        goal="Verileri analiz et, içgörü üret.",
        personality="Meraklı, sayısal.", icon="📊", color="#3b82f6",
        allowed_tools=["ga4_get_report", "analytics_sales_summary", "trend_detector", "anomaly_detector"],
        allowed_tool_categories=["analytics"],
    ),
    _spec(
        agent_id="growth_agent", name="Growth & Optimization Agent",
        role="Büyüme & Deney",
        goal="CRO, A/B test, bundle, yeni kanal önerileri.",
        personality="Hipotez kuran.", icon="🚀", color="#34d399",
        allowed_tools=["cro_analyzer", "ab_test_designer", "upsell_opportunity_finder", "bundle_designer"],
        allowed_tool_categories=["growth"],
    ),
    _spec(
        agent_id="compliance_agent", name="Marketplace Compliance Agent",
        role="Pazaryeri Uyumluluk",
        goal="Listelerin pazaryeri kurallarına uygunluğunu kontrol et.",
        personality="Titiz.", icon="🛡️", color="#ef4444",
        allowed_tools=["listing_compliance_check", "forbidden_word_scanner"],
        allowed_tool_categories=["compliance"],
        escalation_threshold=0.7,
    ),
    _spec(
        agent_id="legal_compliance_agent", name="Legal & Compliance Agent",
        role="Hukuki Uyum & Sözleşme",
        goal="KVKK, mesafeli satış, gizlilik politikası.",
        personality="Titiz, risk azaltıcı.", icon="⚖️", color="#94a3b8",
        allowed_tools=["kvkk_compliance_checker", "return_policy_generator", "privacy_policy_generator"],
        allowed_tool_categories=["legal"],
        escalation_threshold=0.7,
    ),
    _spec(
        agent_id="negotiation_agent", name="Negotiation Agent",
        role="Müzakere & Anlaşma",
        goal="Tedarikçi/partner müzakerelerini BATNA/ZOPA temelli yürüt, optimum anlaşmaya var.",
        personality="Stratejik, sabırlı, veri odaklı müzakereci.", icon="🤝", color="#0ea5e9",
        allowed_tools=[
            "supplier_negotiation_simulator", "counter_offer_generator", "deal_evaluator",
            "competitor_price_lookup", "cogs_calculator", "agent_handoff",
        ],
        allowed_tool_categories=["negotiation", "product", "pricing"],
        can_delegate_to=["product_development_agent", "pricing_agent"],
        escalation_threshold=0.7,
    ),
    _spec(
        agent_id="logistics_agent", name="Logistics Coordination Agent",
        role="Lojistik Koordinasyon",
        goal="Çok kanallı kargo seçimi, rota optimizasyonu ve gönderi takibini koordine et.",
        personality="Operasyonel, hız & maliyet dengesini gözeten.", icon="🚚", color="#14b8a6",
        allowed_tools=[
            "carrier_rate_comparator", "route_optimizer", "shipment_tracking_aggregator",
            "order_list", "stock_levels_query", "agent_handoff",
        ],
        allowed_tool_categories=["logistics", "order", "stock"],
        can_delegate_to=["operations_agent"],
    ),
    _spec(
        agent_id="dynamic_pricing_agent", name="Dynamic Pricing Agent",
        role="Dinamik Fiyatlandırma",
        goal="Talep, rakip ve stok sinyallerinden anlık fiyat ayarı öner; rekabetçi & kârlı kal.",
        personality="Tepkisel, esneklik (elasticity) odaklı.", icon="📈", color="#f59e0b",
        allowed_tools=[
            "dynamic_price_engine", "competitor_price_monitor", "demand_signal_aggregator",
            "margin_calculator", "competitor_price_lookup", "agent_handoff",
        ],
        allowed_tool_categories=["dynamic_pricing", "pricing"],
        can_delegate_to=["pricing_agent", "analytics_agent"],
        escalation_threshold=0.65,
    ),
    _spec(
        agent_id="autonomous_decision_agent", name="Autonomous Decision Agent",
        role="Otonom Karar Koordinatörü",
        goal="Ajanlar arası önerileri birleştir, otonomi politikasını uygula, eşik altı kararları otomatik onayla.",
        personality="Politika bilinçli, risk azaltıcı, izlenebilir.", icon="🧭", color="#a855f7",
        allowed_tools=[
            "autonomy_policy_check", "decision_log_writer", "deal_evaluator", "agent_handoff",
        ],
        allowed_tool_categories=["decision"],
        can_delegate_to=[
            "negotiation_agent", "logistics_agent", "dynamic_pricing_agent",
            "pricing_agent", "operations_agent",
        ],
        approval_authority=["price_change_under_5_pct", "carrier_switch_under_500_try"],
        escalation_threshold=0.75,
    ),
    _spec(
        agent_id="influencer_pr_agent", name="Influencer & PR Agent",
        role="Influencer & Medya İlişkileri",
        goal="Influencer keşfet, brief hazırla, PR yönet.",
        personality="İlişki odaklı.", icon="🎙️", color="#fb7185",
        allowed_tools=["influencer_discovery", "influencer_outreach_writer", "press_release_writer"],
        allowed_tool_categories=["influencer"],
    ),
]
